# alembic/versions/2d207efbb69b_add_status_column_to_receipt.py
"""Add status column to Receipt

Revision ID: 2d207efbb69b
Revises: de8cc1c25e5e
Create Date: 2025-07-28 12:03:33.034239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# --- PENTING: Import Enum yang baru Anda buat ---
import enum
from sqlalchemy import Enum as SQLAEnum # Alias untuk menghindari konflik nama jika ada Enum lain

# Definisikan Enum di sini agar Alembic bisa mengenali tipe datanya
class ReceiptStatusEnum(enum.Enum):
    pending = "pending"
    paid = "paid"
    failed = "failed"
    cancelled = "cancelled"
    expired = "expired"

# revision identifiers, used by Alembic.
revision: str = '2d207efbb69b'
down_revision: Union[str, None] = 'de8cc1c25e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- PERBAIKAN UNTUK artworks.is_sold (dari error NotNullViolation) ---
    # 1. Update nilai NULL yang ada di kolom 'is_sold' menjadi FALSE
    op.execute(
        sa.text("UPDATE artworks SET is_sold = FALSE WHERE is_sold IS NULL")
    )
    # 2. Ubah kolom 'is_sold' menjadi NOT NULL
    op.alter_column('artworks', 'is_sold',
                    existing_type=sa.BOOLEAN(),
                    type_=sa.BOOLEAN(),
                    nullable=False,
                    existing_comment=None,
                    postgresql_using='is_sold::boolean') # Penting untuk PostgreSQL jika ada tipe data Boolean yang tidak standar


    # --- TAMBAHAN: Menambahkan kolom 'status' ke tabel 'receipts' ---
    # 1. Buat tipe ENUM di PostgreSQL (jika belum ada)
    #    Alembic autogenerate kadang tidak selalu menyertakan ini jika tipe sudah ada atau diinferensi.
    #    Jika Anda yakin Alembic sudah mengurusnya, baris ini bisa di-komentar.
    #    Namun, untuk memastikan, lebih baik tambahkan.
    op.execute(
        "CREATE TYPE receiptstatusenum AS ENUM ('pending', 'paid', 'failed', 'cancelled', 'expired')"
    )

    # 2. Tambahkan kolom 'status' ke tabel 'receipts'
    op.add_column('receipts', sa.Column('status', SQLAEnum(ReceiptStatusEnum, name='receipt_status_enum'), server_default='pending', nullable=False))

    # 3. Update nilai default untuk baris 'receipts' yang sudah ada
    #    Ini penting jika Anda sudah memiliki data di tabel 'receipts'
    op.execute(
        sa.text("UPDATE receipts SET status = 'pending' WHERE status IS NULL")
    )


    # --- PENTING: Hapus baris op.drop_table() yang tidak diinginkan dari autogenerate ---
    # Baris-baris ini sangat merusak karena akan menghapus data Anda.
    # Jika Anda ingin mengelola tabel 'purchases' atau 'likes', buat migrasi terpisah.
    # op.drop_table('receipts') # DIHAPUS
    # op.drop_table('purchases') # DIHAPUS
    # op.drop_table('likes') # DIHAPUS


    # --- Perubahan lain yang mungkin di-autogenerate (tetap biarkan jika relevan) ---
    op.alter_column('receipts', 'buyer_secret_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- Revert perubahan pada kolom 'artworks.is_sold' ---
    op.alter_column('artworks', 'is_sold',
                    existing_type=sa.BOOLEAN(),
                    nullable=True) # Kembali ke nullable=True

    # --- Hapus kolom 'status' dari tabel 'receipts' ---
    op.drop_column('receipts', 'status')
    # Hapus tipe ENUM dari PostgreSQL saat downgrade
    op.execute(
        "DROP TYPE receiptstatusenum"
    )

    # --- PENTING: Hapus baris op.create_table() yang tidak diinginkan dari autogenerate ---
    # Ini adalah kebalikan dari op.drop_table() di upgrade yang sudah dihapus.
    # op.create_table('likes', ...) # DIHAPUS
    # op.create_table('purchases', ...) # DIHAPUS
    # op.create_table('receipts', ...) # DIHAPUS (karena di upgrade kita add_column, bukan drop/create)

    # --- Perubahan lain yang mungkin di-autogenerate (tetap biarkan jika relevan) ---
    op.alter_column('receipts', 'payment_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('receipts', 'buyer_secret_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###